export { LeftClipPath} from "./LeftClipPath"
export {RightClipPath} from "./RightClipPath"
export {CercleClipPath} from "./CercleClipPath"
export { PolygonClipPath} from "./PolygonClipPath"
export {RightTopClipPath} from "./RightTopClipPath "